### ISSUE TITLE
samtools faidx time

### ISSUE THREAD

**Issue by DavideBrex** [fansalon/TEspeX#4]
Hello,
thank you for developing such an interesting tool! I wanted to give it a try and test it with my onw data.
I started running it 3 days ago but it is still at the step of creating the index from the reference transcriptome (samtools faidx).
I guess this is not related to your tool of course but I was wondering whether such long time is to be expected. 
For the input files (cdna,ncdna an TEs) I followed your guidelines and tutorial. 
Thank you!
Davide

**Comment by fansalon** [comment]
Hi Davide,

thank you very much for using TEspeX and thanks for reporting this issue!

The tool is supposed to be quite quick and it sounds like something is not working properly if the transcriptome indexing alone is taking 3 days.

I would suggest some controls as follow:

1. how many transcripts does the transcriptome contain? (grep -c ">" TE_transc_reference.fa)
2. what happens if you run the indexing by yourself? (samtools faidx TE_transc_reference.fa)
3. could you please send me the results of "ls <TEspeX out>"?
4. could you please send me the Log file?
5. would you mind sharing the transcriptome file (it should be something named "TE_transc_reference.fa")

Thank you very much.
Federico

**Comment by DavideBrex** [comment]
Hi Federico,
thank you for your fast reply!
There are 247097 sequences in TE_transc_reference.fa
I tried to run it by myself and it works, I get the index in few seconds. 
The content of my  output directory is just the log file and TE_transc_reference.fa
[Here ](https://drive.google.com/drive/folders/1y-kJhyO5lLUlulSSXlSo8McxzY1BVKrg?usp=sharing) you can find these files.
Thank you again for your support,

Davide

**Comment by fansalon** [comment]
Hi Davide,

thanks for sharing the files. Everything seems good to me!

I have tried to run it on my slurm system, and everything run smoothly.

At this point what I would do is to kill the job and relaunch it. Maybe the node itself has experienced some issues?

If this still does not work, would you mind sharing the 3 input fasta files separately?

Some additional questions:
1. On which system are you running TEspeX (slurm, pbs, ..)?
2. Are you running it by using the TEspeX.py or the wrapper*py?
3. Which TEspeX version are you using?

Thank you,
Federico

**Comment by DavideBrex** [comment]
Hi Federico,
Mhh this is weird. I tried to relaunch it but still it gets stuck in the indexing step. I am running  TEspeX.py on a server of the university without a queuing system. The version is 1.2.1.  
Also wanted to mention that the testing step (as mentioned in the documentation) runs smoothly. 
If I copy paste and run the samtools command that is printed in the log files it works.
I will upload the 3 input files in the drive folder so you can find them.
Thank you again for your help!
Best,
Davide

**Comment by fansalon** [comment]
Ok, I did some tests and found out what the problem was. As you may have noticed, when you run samtools index by yourself, you get many warnings reporting duplicated sequences. It seems like these warnings generates some issues to the subprocess TEspeX uses to make the system call.

The duplicated sequences you have *should* be deriving from the transcript files from gencode. 
Gencode has three types of transcript files (https://www.gencodegenes.org/human/):
1. Transcript sequences ("gencode.v42.transcripts.fa")
2. Protein-coding transcript sequences ("gencode.v42.pc_transcripts.fa")
3. Long non-coding RNA transcript sequences ("gencode.v42.lncRNA_transcripts.fa")

The fasta files named "gencode.v42.transcripts.fa" and "gencode.v42.lncRNA_transcripts.fa" contains some redundancies that seem to generate some problems to subprocess, as reported above.
The files that should be used instead are the "gencode.v42.pc_transcripts.fa" and "gencode.v42.lncRNA_transcripts.fa", which should not contain redundancies.

Could you download these two files and retry?

If you confirm this runs smoothly, I will explicitly specify in the manual which files have to be downloaded and modify TEspeX such as when duplicated transcripts are found in the input fasta files an error is generated instead of staying stuck forever.

Hope this helps!

Thanks for reporting the bug!
Federico

**Comment by DavideBrex** [comment]
Hi Federico!
Yes now it works! Thank you for taking the time to help me out :)
Best,
Davide

**Comment by fansalon** [comment]
Hi Davide,

I have modified TEspeX in order to stop and print a message when duplicated sequence headers are found in the input files.

Could you please install the TEspeX latest version (2.0.0) and confirm me that when run with the files you were originally using the process is killed and does not run forever?

Many thanks,
Federico

**Comment by fansalon** [comment]
Apologies: 2.0.1 is the latest version
